services:
  website:
    environment:
      HOST: "0.0.0.0"
      PORT: "4321"
    # Always rebuild after pulling changes
    pull_policy: build
    build: .
    container_name: website
    restart: unless-stopped
    working_dir: /app
    ports:
      - '8443:4321'
    command: bun --bun run server.ts